### ISSUE TITLE
The Roswell Course

### ISSUE THREAD

**Issue by jkushner33** [frolfr/frolfr-android#1]
Dear Willy,

The Roswell course is known far and wide as the most annoying, frustrating course this side of the Mason-Dixon.  Why is Frolfr supporting such an awful course?  

Who do you think you are? What gives you the right?

Thanks,
Secret Admirer

**Comment by willieowens** [comment]
Mr. Kushner,

I am unable to reproduce - Roswell seemed like a fine course for the capable player. Please submit screenshots or a short video clip so we can better identify the source of your frustration.

Best,
Your Admired
